version: "3.9"
services:
    server:
        build: server
        container_name: server
        restart: unless-stopped
        depends_on:
          - database
        volumes:
          - media:/var/lib/aperturama/media
        environment:
          - LISTEN_PORT=${LISTEN_PORT}
          - DB_HOST=${DB_HOST}
          - DB_USERNAME=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
          - DB_DATABASE=${DB_DATABASE}
          - MEDIA_ROOT=/var/lib/aperturama/media
          - JWT_KEY=${JWT_KEY}
        ports:
          - ${LISTEN_PORT}:${LISTEN_PORT}
    database:
        image: postgres
        container_name: database
        restart: unless-stopped
        volumes:
          - db:/var/lib/postgresql/data
          - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
          - POSTGRES_USER=${DB_USERNAME}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
          - POSTGRES_DB=${DB_DATABASE}
        ports:
          - "5432:5432"
volumes:
    db:
        driver: local
    media:
        driver: local
